### ISSUE TITLE
Model for HD

### ISSUE THREAD

**Issue by azadsoni66** [JyChen9811/DOC-VTON#1]
Does the same model work for HD images, Or do we need to retrain it for HD images case ?

**Comment by Anuj58** [comment]
Same question, Can someone please answer this how can we test the model on HD images, it does work very well only on low-quality photos.

**Comment by Anuj58** [comment]
@JyChen9811 Need your help here

**Comment by JyChen9811** [comment]
Hello, we provide the pre-trained model trained on 256 x 192 image resolution. For HD images, you could retrain the model with the auxiliary components of HD-VTON, provided in the section "Auxiliary test data".

**Comment by Hanjunzhe** [comment]
@Anuj58 May I ask if this code can be downloaded and run directly? Where should the downloaded dataset and pre trained model be placed？
