### ISSUE TITLE
how to get test data ?

### ISSUE THREAD

**Issue by Gzzgz** [JyChen9811/DOC-VTON#2]
![企业微信截图_c0c98e06-61df-4e30-83e7-7d8dd5752a31](https://user-images.githubusercontent.com/15968092/231137687-f58a1ca1-fd45-436f-9c4d-6cbc591f6955.png)

**Comment by JyChen9811** [comment]
Hello，you could fetch the test data from https://drive.google.com/file/d/1tE7hcVFm8Td8kRh5iYRBSDFdvZIkbUIR/view
